apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: crudapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: pallavitarke04/backend-crudapp:latest
        ports:
        - containerPort: 4000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: PORT
          value: "4000"
        - name: MONGO_URI
          value: "mongodb://cruduser:crudpass@mongo-0.mongo:27017,mongo-1.mongo:27017,mongo-2.mongo:27017/crudapp?replicaSet=rs0&authSource=crudapp"
        - name: REDIS_NODES
          value: "redis-0.redis:6379,redis-1.redis:6379,redis-2.redis:6379,redis-3.redis:6379,redis-4.redis:6379,redis-5.redis:6379"
        - name: REDIS_PASSWORD
          value: "pass123"

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: crudapp
spec:
  selector:
    app: backend
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 32000   # pick a free port
  type: NodePort
  