apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: crudapp
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
    - name: client       # required
      port: 6379
    - name: gossip       # required
      port: 16379

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: crudapp
spec:
  serviceName: redis
  replicas: 6
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.2
        command: ["redis-server", "/etc/redis/redis.conf"]
        ports:
        - containerPort: 6379
        - containerPort: 16379
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 500Mi
