apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: crudapp
data:
  redis.conf: |
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000
    appendonly yes
    requirepass pass123
    masterauth pass123
